### ISSUE TITLE
Enhancement: Make this work non-interactively

### ISSUE THREAD

**Issue by robbratton** [allynl93/PS-SAML-Interactive#1]
As a PowerShell developer, I would like to be able to authenticate using SAML in a background process without requiring a Windows form so I can run my scripts as a scheduled task when the user is not logged in.

**Comment by allynl93** [comment]
Hi, sorry for the delay in responding. 
I don't know how SAML Auth can be completed non-interactively, especially if MFA is enabled.
Depending on the environment it may be possible for the auth to be non-interactive for example if Kerberos and no MFA etc.
