### ISSUE TITLE
could a sample be included that calls auth/saml/logon after?

### ISSUE THREAD

**Issue by maurice-cote** [allynl93/PS-SAML-Interactive#2]
We keep getting errors when reusing the received samlresponse and sadly there are no logs created on the server.

**Comment by allynl93** [comment]
Hi, sorry for the delay in responding.
If this is CyberArk related, the first thing I would do is ensure that IDP initiated login is enabled within the PVWA. Without adding this attribute to the PVWA web.config then auth will fail.
Basically this script is just looking for the auth/saml/logon post request and taking the contents of that post request.
