### ISSUE TITLE
Hanging PowerShell ISE After Run

### ISSUE THREAD

**Issue by Bigjohnny89** [allynl93/PS-SAML-Interactive#4]
I have noticed that ISE tends to hang very shortly after this module has been run.  In research, there seems to be a known issue around Windows forms and how they are executed in the code (https://stackoverflow.com/questions/30808084/using-windows-forms-locks-up-powershell-ise-minutes-after-script-has-terminated).  After changing line 56 from:

if($form.ShowDialog() -ne "OK") {

to:

if([system.windows.forms.application]::run($form) -ne "OK") {	

it appears the issue with ISE locking up has been addressed.

**Comment by allynl93** [comment]
Thank you for this information!
Will take a look with a view to update the module.

**Comment by allynl93** [comment]
Fix implemented
