### ISSUE TITLE
Use different browser

### ISSUE THREAD

**Issue by Janzijls** [allynl93/PS-SAML-Interactive#5]
The system.web element used by the script uses Internet Explorer. Internet Explorer is discontinued by Microsoft.
Is it possible to modify the script to use a different browser, like Edge?

**Comment by allynl93** [comment]
Hi, this has been something I have been working on for a few weeks and have just published. 
There is now a pre-built release of an app which is focused towards CyberArk PVWA which you can download and use. It uses webView2 which is the browser framework used by edge.
If you are not focused on CyberArk then you can build from source and make changes to to fit your requirements.
I hope this helps.

**Comment by Janzijls** [comment]
Thank you for this solution. However, when we use the pre-built executable and use the $loginResponse with New-PASSession  we get the following error:
Invoke-PASRestMethod : [400] Authentication failure. Please contact your Administrator.

Manual logon to the PVWA in the webbrowser using ADFS works fine. The $loginResponse has the samlresponse value, however the application does not seem to accept it.
We use ADFS and PAM on-premises. We added the EnableIdPInitiatedSso setting to the PVWA.
Is there anything we could try to make this work?

**Comment by allynl93** [comment]
Hi, couple questions:

- Did it work previously using the PowerShell module?
- Does IDP imitated login work via the browser (not via the SAML button on the PVWA)

**Comment by Janzijls** [comment]
Hi,

The getSAMLResponse-Interactive via IE doesn’t  work because of an error using ADFS with IE (No style sheet is configured in the active theme for default locale).
However, the idpinitiatedsignon via the browser in Edge is working fine. Also, New-Passession with the same account is working fine when using LDAP as authentication method.
