### ISSUE TITLE
Cyberark Cloud

### ISSUE THREAD

**Issue by grvs1404** [allynl93/PS-SAML-Interactive#7]
Hey Allyn,
Would I need to use the EXE version or the PS version of this to get this setup for the cloud instance of Cyberark?

We are in process of migrating to the cloud version of Cyberark and I am attempting to get our script to function like it did with the onprem version of cyberark. 

I downloaded the getSAMLResponse.exe.v1.zip and i noticed you said that for another app it might have to be built for the app itself, wasnt sure if cloud vs on prem would be any different. (I would think not but im not positive).

When attempting to use the exe I received an error box with the details below.

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at getSAMLResponse.Form1.WebView_CoreWebView2InitializationCompleted(Object sender, CoreWebView2InitializationCompletedEventArgs e) in C:\Users\allyn\source\repos\getSAMLResponse\getSAMLResponse\Form1.cs:line 23
   at Microsoft.Web.WebView2.WinForms.WebView2.<InitCoreWebView2Async>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at getSAMLResponse.Form1.<InitializeAsync>d__2.MoveNext() in C:\Users\allyn\source\repos\getSAMLResponse\getSAMLResponse\Form1.cs:line 46
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4614.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
getSAMLResponse
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/Cyberark/getSAMLResponse.exe.v1/getSAMLResponse.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4550.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4614.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Microsoft.Web.WebView2.WinForms
    Assembly Version: 1.0.1518.46
    Win32 Version: 1.0.1518.46
    CodeBase: file:///D:/Cyberark/getSAMLResponse.exe.v1/Microsoft.Web.WebView2.WinForms.DLL
----------------------------------------
CrowdStrike.Sensor.ScriptControl
    Assembly Version: 6.54.16810.0
    Win32 Version: 6.54.16810.0
    CodeBase: file:///C:/Windows/SysNative/CrowdStrike.Sensor.ScriptControl16810.dll
----------------------------------------
Microsoft.Web.WebView2.Core
    Assembly Version: 1.0.1518.46
    Win32 Version: 1.0.1518.46
    CodeBase: file:///D:/Cyberark/getSAMLResponse.exe.v1/Microsoft.Web.WebView2.Core.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4380.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4614.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4161.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by allynl93** [comment]
Hi,
Are you using the same IDP for your cloud instance as on-prem? If you are then the PowerShell module should continue to work. The only thing that might be impacting you is the fact that the PVWAs in PCloud are managed... For the module to work you need to enable IDP-initiated auth which on-prem is done in a config file... You will need to ask CyberArk if this can be enabled in PCloud... If not then the modules won't work, unfortunately...

**Comment by grvs1404** [comment]
Ahh, I will look into that thank you!
